import type { AstroData } from './types';

export const initialData: AstroData = {
  name: 'ശ്രീദേവി',
  dob: '1990-05-15',
  tob: '10:30',
  pob: 'തൃശൂർ',
  gender: 'female',
  predictions: '',
  age: '34',
  nakshatra: 'പൂയം',
  address: 'ശ്രീവിലാസം, കോട്ടയം',
  email: 'sreedevi@example.com',
  malayalamMonth: 'ഇടവം',
  arudhamRashi: 'ചിങ്ങം',
  deepam: 'നെയ് വിളക്ക്',
  prasnaChintha: 'പ്രശ്നചിന്ത വിശദാംശങ്ങൾ ഇവിടെ ചേർക്കുക',
  thamboolamRashi: 'കുംഭം',
  thamboolam: 'വെറ്റില',
  thamboolamGrahangal: 'ശനി',
  udayaRashikal: 'മിഥുനം',
  lagnaNavamsakam: 'തുലാം',
  spashtangaRashi: 'വൃശ്ചികം',
  chandrarishti: 'ഉണ്ട്',
  pariharangal: 'ദോഷപരിഹാരങ്ങൾ ഇവിടെ ചേർക്കുക',
};
